language: node_js

node_js:
    - "10"
    - "6.0"

branches:
    only:
        - master
        - dev

git:
    depth: 3
    quiet: true

before_script:
    - make setup_cover

script:
    - make run_test

after_script:
    - make send_cover

notifications:
    email: false
